#define LIGHT_NO_CMD 0
#define LIGHT_OFF 1
#define LIGHT_ON 2
#define LIGHT_BRIGHTER 3
#define LIGHT_DIMMER 4

#define TILT_OFF 0
#define TILT_CENTER 1
#define TILT_UP 2
#define TILT_DOWN 3
#define TILT_INITIALIZE 4

#define GRIPPER_STOP 1
#define GRIPPER_OPEN 2
#define GRIPPER_CLOSE 3

#define MENU_NO_CMD 0
#define MENU_CANCEL 1
#define MENU_DISPLAY 2
#define MENU_SELECT 3
#define MENU_CANCEL_SUBMENU 4

#define OVERLAY_NO_CMD 0
#define OVERLAY_TOP 1
#define OVERLAY_BOTTOM 2
#define OVERLAY_OFF 3

#define REQUEST_VIDEO 0x23
#define REQUEST_MOTOR 0x24
#define REQUEST_SENSOR 0x25
#define REQUEST_NAVIGATION 0x26
#define REQUEST_LIGHTS 0x27
#define REQUEST_THRUSTER 0x28
#define REQUEST_ACCESSORY 0x29
#define REQUEST_TILT 0x2A
#define REQUEST_BOARD_FIRMWARE 0x2B
#define REQUEST_BACKPLANE_FIRMWARE 0x2C

#define JOYSTICK_LIMIT 1000

#define LIGHT1_NUMBER 1
#define LIGHT2_NUMBER 5
#define GRIPPER_NUMBER 0

#define RESPONSE_TIMEOUT 100     // Milliseconds

